server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # serve static files and fallback to index.html for SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }
}
